[package]
name = "topaz"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
home = "0.5.3"
once_cell = "1.7.2"
hotwatch = "0.4.6"
